swagger: '2.0'
info:
  title: Freefeed API
  version: "3.0.0-alpha"
host: freefeed.net
basePath: /v3
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json

paths:
  $ref: './paths/index.yaml'

parameters:
  $ref: './parameters/index.yaml'

responses:
  $ref: './responses/index.yaml'

definitions:
  $ref: './definitions/index.yaml'